apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: cloud-native-go
  labels: 
    app: cloud-native-go
spec:
  replicas: 2
  template:
    metadata: 
      labels:
        app: cloud-native-go
        tier: service
    spec:
      containers: 
      - name: cloud-native-go
        image: cloud_native_go:1.0.4-alpine
        ports: 
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"